language: minimal
services:
- docker

before_install:
- docker build -t ebay/goose/test . --target test
- docker build -t ebay/goose .

script:
- docker run ebay/goose/test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main
